name: task

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0,5,12 * * *'


jobs:
  task:
    name: im fine
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y openvpn curl
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Setup VPN
        run: |
          sudo chmod 777 client.conf
          sudo cp client.conf /etc/openvpn/
          sudo chmod 777 pass
          sudo cp pass /etc/openvpn/
          sudo ls /etc/openvpn/
      - name: Run
        run: |
          sudo service openvpn@client start
          curl ifconfig.co
          sleep 30
          curl ifconfig.co
          python ./main.py "${{ secrets.USER_1 }}" "${{ secrets.PASS_1 }}" "" "${{ secrets.MAIL_SERVER }}" "${{ secrets.MAIL_LOGIN }}" "${{ secrets.MAIL_PASS }}" "${{ secrets.RECV_1 }}"
          sleep 30
          python ./main.py "${{ secrets.USER_2 }}" "${{ secrets.PASS_2 }}" "" "${{ secrets.MAIL_SERVER }}" "${{ secrets.MAIL_LOGIN }}" "${{ secrets.MAIL_PASS }}" "${{ secrets.RECV_2 }}"
          sleep 30
          python ./main.py "${{ secrets.USER_3 }}" "${{ secrets.PASS_3 }}" "" "${{ secrets.MAIL_SERVER }}" "${{ secrets.MAIL_LOGIN }}" "${{ secrets.MAIL_PASS }}" "${{ secrets.RECV_3 }}"